### ISSUE TITLE
Works only Vue.js 2.0

### ISSUE THREAD

**Issue by andre-dw** [dalphyx/vue-headroom#1]
The mounted function used to set the scroll and height only works in Vue 2.0.
I use it in Vue 1.0.27 and changed it to ready.

**Comment by dalphyx** [comment]
@andre-dw Yes, this component support Vue 2.0 only, just because I don't use Vue 1.0 anymore. So, feel free to modify it to suit your need. Anyway, still recommend you switch Vue from 1.0 to 2.0 :)
