### ISSUE TITLE
tolerance

### ISSUE THREAD

**Issue by samburgers** [dalphyx/vue-headroom#10]
Hi, 

I can't seem to add separate values to both `upTolerance` and `downTolerace`. cheers

**Comment by dalphyx** [comment]
@samburgers   Any link?

**Comment by samburgers** [comment]
My bad, it actually may have just been the extreme values i was testing with. The below more sensible values appear to work. Thanks again :)
```
<vue-headroom
                :offset="500"
                :speed="400"
                :upTolerance="1"
                :downTolerance="50"
                :onUnpin="handleUnPin"
                :onTop="handleTop"
                :onNotTop="handleNotTop">
</vue-headroom>
