### ISSUE TITLE
Add classes on initial load.

### ISSUE THREAD

**Issue by samburgers** [dalphyx/vue-headroom#11]
Hi again, this package doesn't appear to add the headroom specific classes until the user scrolls. The behaviour of the original headroom adds these on load. The `headroom--top` class is the one that I need to target. Many thanks!

Demos to compare:

http://wicky.nillia.ms/headroom.js/

and

https://dalphyx.github.io/vue-headroom/

cheers

**Comment by dalphyx** [comment]
@samburgers  the behaviour of vue-headroom calculate the state and  add classes on load that same with react-headroom . Unlike headroom.js it just add classes.
