### ISSUE TITLE
ssr中没有效果？

### ISSUE THREAD

**Issue by susansjy** [dalphyx/vue-headroom#12]
你好，最近在尝试基于nuxt的ssr开发，发现在后端渲染中vue-headroom没有效果？

想应该是后端渲染没有window的缘故，暂未发现解决办法，是否考虑支持ssr?

**Comment by dalphyx** [comment]
@susansjy 可以在nuxt的plugin中先配置ssr: false用用。ssr支持的话我这边之后再看看。

**Comment by dalphyx** [comment]
更新ssr支持，应该可以在nuxt中正常使用:)
