### ISSUE TITLE
_vm.start is not a function

### ISSUE THREAD

**Issue by nitzyan** [dalphyx/vue-headroom#15]
I'm getting an error with vue 2.5.2 and vue-headroom. Headroom seems to be working as intended, but I'm still getting this error. This error is accompanied by 
`Property or method "start" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. `

I've setup up everything as described and using vue-cli boilerplate. Help would be appreciated.

**Comment by dalphyx** [comment]
@nitzyan you should define a property or method named "start" :)

**Comment by nitzyan** [comment]
Oops! Thanks! :)
