### ISSUE TITLE
How to use scroller prop?

### ISSUE THREAD

**Issue by l2aelba** [dalphyx/vue-headroom#17]
Can you give me an example how to use `scroller` ?

```html
<headroom :scroller="...."></headroom>
```

Thanks thanks :D

**Comment by jdvivar** [comment]
Check the code for the prop definition:
https://github.com/dalphyx/vue-headroom/blob/master/src/headroom.vue#L42

You need to provide a function that returns the object were you want headroom to listen for scroll events. The default function returning the `window` object is usually ok. So by default you probably don't need to use the `:scroller` prop.

**Comment by l2aelba** [comment]
Aha thanks. Closed
