### ISSUE TITLE
Emit event instead of props

### ISSUE THREAD

**Issue by RomainFrancony** [dalphyx/vue-headroom#19]
Hi, currently some event are used with both `$emit` and props (pin, unpin) but some others are used with props only (bottom, top, ...).
 Shouldn't it be better is they were all using the `$emit` since it's the "appropriate" solution to manage events in Vue ?

**Comment by dalphyx** [comment]
@RomainFrancony we can use both props and $emit :)

**Comment by dalphyx** [comment]
Use emit event in v0.10.1 :)
