### ISSUE TITLE
content body flashing when headroom element is initialized

### ISSUE THREAD

**Issue by h404bi** [dalphyx/vue-headroom#20]
Fast network.
![rt1](https://user-images.githubusercontent.com/5764917/55334193-5acd2980-54cb-11e9-906b-22ddf3940727.gif)

Slow network. Did you see that?
![rt](https://user-images.githubusercontent.com/5764917/55334208-602a7400-54cb-11e9-98df-a291f8e1ba52.gif)

I checked the vanilla headroom.js and the flashing issue does not occur.

**Comment by dalphyx** [comment]
@h404bi  You can try new version :)

**Comment by chawyehsu** [comment]
@dalphyx Thanks for quick fix, awesome!
